name: ude_dev_test
version: '2.0.0'
config-version: 2

model-paths: ['models']
snapshot-paths: ['snapshots']
test-paths: ['tests']
macro-paths: ['macros']
analysis-paths: ['analyses']

models:
  ude_dev_test:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: incremental
      +schema: marts

snapshots:
  ude_dev_test:
    +target_schema: snapshots
    +strategy: timestamp

vars:
  batch_id: null
  quarantine_schema: quarantine
