ude_dev_test:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: duckdb
      path: /tmp/ude_dev_test_dev.duckdb
      threads: 4

    prod:
      type: bigquery
      method: oauth
      project: 12345
      dataset: dbt_prod
      threads: 4
      timeout_seconds: 300
      location: US
